// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"fr": &dictionary{index: frIndex, data: frData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Invalid PIN":                       1,
	"PIN accepted, joining the call...": 2,
	"Please enter your PIN followed by # (use * to delete)\nEntered: %s": 0,
	"Screen sharing has ended":        4,
	"You are the only participant...": 3,
}

var enIndex = []uint32{ // 6 elements
	0x00000000, 0x00000045, 0x00000051, 0x00000073,
	0x00000093, 0x000000ac,
} // Size: 48 bytes

const enData string = "" + // Size: 172 bytes
	"\x02Please enter your PIN followed by # (use * to delete)\x0aEntered: %[" +
	"1]s\x02Invalid PIN\x02PIN accepted, joining the call...\x02You are the o" +
	"nly participant...\x02Screen sharing has ended"

var frIndex = []uint32{ // 6 elements
	0x00000000, 0x00000052, 0x00000064, 0x0000008d,
	0x000000af, 0x000000c7,
} // Size: 48 bytes

const frData string = "" + // Size: 199 bytes
	"\x02Veuillez saisir votre code PIN suivi de # (utilisez * pour effacer)" +
	"\x0aSaisi : %[1]s\x02Code PIN invalide\x02Code PIN accepté, connexion en" +
	" cours...\x02Vous êtes le seul participant...\x02Fin du partage d'écran"

	// Total table size 467 bytes (0KiB); checksum: 670064F7
